#!/bin/bash
clear
echo -e "\033[1;31mMegaTúnel VPS - ajuda\033[0m"
echo -e "\033[1;37m © Rodney Costa - Tomada M. \033[1;37mPara sair (de qualquer lugar) Ctrl + C\033[1;33m

Li \033[1;30m(Nesta opção é possível definir um limite de conexões para cada usuário. Basta digitar Li e depois digitar o nome do usuário que você quer definir um limite e depois o número correspondente à quantidade de logins.\033[1;33m

Uc \033[1;30m(Nesta opção é possível criar um novo usuário e senha, definir a data de expiração e limite de logins \033[1;36m(novo) \033[1;33m

Ub \033[1;30m(Pode acontecer que no monitor de conexões conste que um usuário está conectado sem que esteja e assim a reclamação do cliente por causa da queda de conexão é inevitável. Com esta opção você pode desconectar qualquer usuário conectado ou que consta está conectado. Também é possível deletar qualquer usuário. Redefinir a data de um usuário.\033[1;36m(aprimorado)\033[1;33m

Ah \033[1;30m(Adicionar novos Hosts de operadoras e terceiros aceitos pelo squid, caso tenha problemas de conexão com alguma Payload.
Desde que seja um Host aceito pela operadora.)\033[1;33m

Mt \033[1;30m(Monitore as conexões de usuários neste comando. Acompanhe quem está tentando ultrapassar o limite de login e veja quem está conectado em tempo real. Agora ele mostra o limite de login no lado direito.Ele atualiza a cada 5 segundos. Para sair desta sessão tecle Ctrl + c)\033[0m\033[1;33m

Bk \033[1;30m(Backup dos usuários incluindo limite de logins simultâneos e data de expiração\033[1;36m(novo)\033[1;33m Você deve lembrar do local de backup(/etc/mtvps/backup) para uma restauração futura. O usuário que não tiver senha será pedido para definir uma senha no mesmo instante. Salve o em seu celular o backup feito, veja como fazer isso com o fornecedor deste servidor MegaTúnel VPS (@tomada)\033[1;33m

Ru \033[1;30m(Restaurar backup de usuários, caso tenha feito. Digite o local onde está o backup de seus usuários(geralmente em: /etc/mtvps/backup)\033[1;33m

Du \033[1;30m(Exibir informações sobre os usuários já criados, como data, limite, usuário e senha - veja informações sobre um usuário específico \033[1;36m(novo)\033[1;33m

Bn \033[1;30m(Adicionar Banner para ser visualizado por usuários no HTTP INJECTOR por exemplo. Digite a mensagem a ser exibida e tecle enter para salvar)\033[1;33m

Sp \033[1;30m(Realize o teste de velocidade da sua conexão. !Não funciona em todos os servidores!)\033[1;33m

extras \033[1;31m(Apenas para usuários mais avançados. !Se você não conhece sobre as opções deste comando, não mexa!\033[1;36m(novo adicionado)\033[1;33m"

echo -e " \033[40;1;36mCanais no telegram:\033[0m"

echo -e "     \033[40;1;37m De vendas: @MegaTunelVPS  \033[0m"

echo -e "     \033[40;1;37m De Payloads: @MTPayloads  \033[0m"

echo -e "     \033[40;1;37m Diverso: @tomada1  \033[0m"

echo -e "     \033[40;1;36m Contato:  \033[0m"

echo -e "     \033[40;1;37m Telegram: @tomada  \033[0m"

echo -e "     \033[40;1;37m Agradecemos a preferência :) 
Atenciosaente,
MegaTúnel VPS  \033[0m"
exit 0
