#!/bin/bash

clear
echo -e "\033[41;1;37mDetalhes sobre usuários:\033[0m
\033[1;36m1) Ver informações de um usuário específico
2) Ver informações sobre todos os usuários\033[0m"
read -p "opção: " option

 if [ $option -eq 1 ]; then
 read -p "Qual o nome do usuário: " name
if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 clear
 echo -e "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
fi
clear
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuário               Senha              Data E.          Logins S. \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"

if cat /etc/tomada/limite/$name > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/tomada/limite/$name)
else
limitecs="??"
fi

if senha=$(cat /etc/tomada/senha/$name > /dev/null 2> /dev/null)
then
senha=$(cat /etc/tomada/senha/$name)
else
senha="??"
fi

data=$(chage -l $name |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
data="??"
fi

megatuneldata=$(printf '%-18s' "$data")
megatunellimite=$(printf '%-10s' "$limitecs")
megatunelusers=$(printf ' %-21s' "$name")
megatunelpass=$(printf '%-18s' "$senha")
echo -e "\033[1;33m$megatunelusers $megatunelpass $megatuneldata $megatunellimite\033[0m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
exit

if [ $option -eq 2 ]; then
DuT
 exit
 fi

echo -e "\033[1;31mEssa opção não existe!\033[0m"
