#!/bin/bash
clear

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m Usuário               Senha               Data E.          Logins S. \033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do

if cat /etc/tomada/limite/$users > /dev/null 2> /dev/null
then
limitecs=$(cat /etc/tomada/limite/$users)
else
limitecs="??"
fi

if  senha=$(cat /etc/tomada/senha/$users > /dev/null 2> /dev/null)
then
senha=$(cat /etc/tomada/senha/$users)
else
senha="??"
fi

data=$(chage -l $users |grep -i co |awk -F : '{print $2}')
if [ $data = never ] 2> /dev/null
then
data="??"
fi
megatuneldata=$(printf '%-18s' "$data")
megatunellimite=$(printf '%-10s' "$limitecs")
megatunelusers=$(printf ' %-21s' "$users")
megatunelpass=$(printf '%-18s' "$senha")
echo -e "\033[1;33m$megatunelusers $megatunelpass $megatuneldata $megatunellimite\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
done
