#!/bin/bash

echo -e "\033[1;37mOpções avançadas:  \033[1;37mPara Sair Ctrl + C\033[1;33m

Fb \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m

Rf \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m

Ia \033[1;30m(Ferramenta para adicionar novos hosts!!!Não mexa, já vem adicionado por padrão!!!!!)\033[1;33m

Sd \033[1;30m(Detalhes sobre o Sistema operacional[Created BadGuy])\033[1;33m

Re \033[1;30m(Opções para reiniciar o servisso ssh, squid e a própria máquina)

bloquearip \033[1;30m !--Função totalmente experimental--! (Não me pergunte nada!)\033[1;33m"