#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Você não é root"
	echo "Seu usuário esta no grupo sudo"
	echo -e "Para tornar-se root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Você não está como usuário root, nem com seus direitos (sudo)\nPara tornar-se root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/tomada ]
then
echo ""
else
mkdir /etc/tomada
fi

if [ -d /etc/tomada/senha ]
then
echo ""
else
mkdir /etc/tomada/senha
fi

if [ -d /etc/tomada/limite ]
then
echo ""
else
mkdir /etc/tomada/limite
fi
clear
tomada=$ figlet MegaTunel VPS

echo "$tomada"
sleep 2s
clear
echo -e "     \033[40;1;37m CONFIGURAÇÃO MTVPS V.2.0 \033[0m"
echo -e "\033[1;31mNo Span, no DDoS, no Torrent, no fraud. Qualquer desrespeito ou violação dos requisitos impostos pela empresa MegaTúnel, estará sujeito a suspensão definitiva do serviço sem aviso prévio e SEM REEMBOLSO!!!\033[0m"
echo -e "\033[1;37mMenu de opçoẽs:    \033[1;37mPara sair (de qualquer lugar) Ctrl + C\033[1;33m

Li \033[1;30m(Limite de conexões simultâneas)\033[1;33m

Uc \033[1;30m(Criar usuários)\033[1;33m

Ub \033[1;30m(Deletar, Desconectar, Opções. Acesse ajuda e saiba mais)\033[1;33m

Ah \033[1;30m(Adicionar novos Hosts de operadoras e terceiros aceitos pelo squid, caso tenha problemas de conexão com alguma Payload.)\033[1;33m

Mt \033[1;30m(Monitore as conexões por usuários. Acesse ajuda)\033[0m\033[1;33m

Bk \033[1;30m(Backup dos usuários incluindo limite de login simultâneos e data de expiração)\033[1;33m

Ru \033[1;30m(Restaurar backup de usuários, caso tenha feito)\033[1;33m

Du \033[1;30m(Exibir informações sobre os usuários já criados, como data, limite, usuário e senha)\033[1;33m

Bn \033[1;30m(Adicionar Banner para ser visualizado por usuários no HTTP INJECTOR por exemplo)\033[1;33m

Sp \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m

ajuda \033[1;30m(Ajuda sobre o uso deste menú)\033[1;33m

extras \033[1;30m(Para usuários avançados)\033[1;33m"
exit 0
fi