#!/bin/bash

clear
echo -e "\033[41;1;37mOpções:\033[0m"
echo -e "\033[1;36m1) Deletar usuário
2) Mudar a senha do usuário
3) Deletar e desconectar todos do usuário
4) Desconectar todos do usuário
5) Mudar data de expiração de um usuário\033[0m"
read -p "opção: " option

 if [ $option -eq 1 ]; then
 read -p "Qual o nome do usuário: " name
if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
Ub
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo -e "\033[1;37mUsuário \033[1;31m$name\033[0m foi deletado!\033[0m"
 exit
 fi

if [ $option -eq 2 ]; then
 read -p "Qual o nome do usuário: " name
if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
Ub
 fi
 read -p "Qual a nova senha: " pass
 (echo $pass; echo $pass)|passwd $name 2>/dev/null
 echo -e "\033[1;37mA nova senha do usuário \033[1;32m$name\033[0m é: \033[1;32m$pass\033[0m"
 echo "$pass" > /etc/tomada/senha/$name
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Qual o nome do usuário: " name
if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
Ub
 fi
 userdel --force $name > /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo -e "\033[1;37mO usuário \033[1;31m$name\033[0m foi deletado e parado!\033[0m" 
exit
 fi

 if [ $option -eq 4 ]; then
 read -p "Qual o nome do usuário: " name
if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
Ub
 fi
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo -e "\033[1;37mUsuário \033[1;31m$name\033[0m foi parado.\033[0m"
 exit
 fi


 if [ $option -eq 5 ]; then
 read -p "Digite o nome do usuário que quer modificar a data: " name
if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$name\033[0m não existe\033[0m"
 exit
Ub
 fi
 echo "\033[1;37mDigite os dados para a nova data de expiração\033[0m"
 read -p "Dia: " dia
 read -p "Mês(em numeral 1-12): " mes
 read -p "Ano: " ano
 chage -E $ano/$mes/$dia $name 2> /dev/null
 echo -e "\033[1;37mNova data do usuário \033[1;32m$name\033[0m: $dia/$mes/$ano\033[0m"
 exit
 fi

echo -e "\033[1;31mEssa opção não existe.\033[0m"