#!/bin/bash
clear
read -p "Qual o nome do usuário a redefinir: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "\033[1;37mUsuário \033[1;31m$namer\033[0m não existe\033[0m"
 exit
 fi
clear
echo -e "\033[1;26mO que você deseja redefinir ?
1) Número de logins
2) Data de expiração"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
rm /etc/usuarios/$namer.sh
rm /etc/tempo/$namer.sh
limit $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Qual a nova data : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
exit
fi
echo -e "esta opção não existe\033[0m"
